spring.application.name=dental-clinic
spring.profiles.active=dev

# Disable Whitelabel Error Page globally
server.error.whitelabel.enabled=false

# Global Administrator Authentication
app.admin.default.username=${ADMIN_DEFAULT_USERNAME:admin}
app.admin.default.password=${ADMIN_DEFAULT_PASSWORD}

# yyyy-MM-dd format
spring.mvc.format.date=iso