# Base de datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:dental_clinic_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false
