spring.application.name=dental-clinic
spring.profiles.active=dev

# Desactivar Whitelabel Error Page globalmente
server.error.whitelabel.enabled=false

# Autenticacion del Administrador Global
app.admin.default.username=${ADMIN_DEFAULT_USERNAME:admin}
app.admin.default.password=${ADMIN_DEFAULT_PASSWORD}