# PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/dental_clinic_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL en consola (desactivado)
spring.jpa.show-sql=false

# Caché de Thymeleaf
spring.thymeleaf.cache=true

# Credenciales del Super Administrador (variables de entorno)
app.admin.default.username=${ADMIN_DEFAULT_USERNAME}
app.admin.default.password=${ADMIN_DEFAULT_PASSWORD}
